---
abstract: 'drop-in visitor comments support.'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-Comments
provides:
  App::ZofCMS::Plugin::Comments:
    file: lib/App/ZofCMS/Plugin/Comments.pm
    version: 0.0103
requires:
  DBI: 1.602
  HTML::Entities: 1.35
  HTML::Template: 2.9
  Mail::Send: 2.04
  Storable: 2.18
  URI: 1.35
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
